Httprequests
wfiispz/Web-Client pull request #16
Opened 2017-05-13 16:48 UTC by pgruszczynski93

Pull request after merge

2017-05-13 17:26 UTC, PatrykMatwijczuk approved these changes

2017-05-13 18:22 UTC, Dorrin93 requested changes

2017-05-13 18:22 UTC, Dorrin93 commented on PZ/WebClient/Connector.py
> +        return [resources_list, page]
Remove `[]`, when using comma with return statement, python by default will return tuple

2017-05-13 18:22 UTC, Dorrin93 commented on PZ/WebClient/Connector.py
> +        self.url_adr = (endpoint+'/values')
urls should be created / concatenated with `urljoin`:
http://stackoverflow.com/questions/8223939/how-to-join-absolute-and-relative-urls

Be warry though, in this case `'values'` shouldn't begin with `/

2017-05-13 22:47 UTC, Dorrin93 requested changes

2017-05-13 22:47 UTC, Dorrin93 commented on PZ/WebClient/Connector.py
> +        self.url_adr += guid
remove this line

2017-05-13 22:47 UTC, Dorrin93 commented on PZ/WebClient/Connector.py
> +
`from urllib.parse import urljoin`

2017-05-13 22:47 UTC, Dorrin93 commented on PZ/WebClient/Connector.py
> +        self.response = requests.get(self.url_adr)
`self.response = requests.get(urljoin(self.url_adr, guid))`

2017-05-13 22:47 UTC, Dorrin93 commented on PZ/WebClient/Connector.py
> +        self.url_adr += guid
remove this line

2017-05-13 22:47 UTC, Dorrin93 commented on PZ/WebClient/Connector.py
> +    def url_address(self):
useless, remove

2017-05-13 22:47 UTC, Dorrin93 commented on PZ/WebClient/Connector.py
> +    def url_address(self, url_adr):
remove

2017-05-13 22:47 UTC, Dorrin93 commented on PZ/WebClient/Connector.py
> +    def request_args(self):
remove

2017-05-13 22:47 UTC, Dorrin93 commented on PZ/WebClient/Connector.py
> +    def request_args(self, payload):
rename `request_args` to `payload`

2017-05-13 22:47 UTC, Dorrin93 commented on PZ/WebClient/Connector.py
> +        self.url_adr = url_adr
add underscore `_` before all members to make them private
`self._url_address = url_address`

2017-05-13 22:47 UTC, Dorrin93 commented on PZ/WebClient/Connector.py
> +        self.response = requests.delete(self.url_adr)
self.response = requests.delete(urljoin(self.url_adr, guid))

2017-05-13 22:47 UTC, Dorrin93 commented on PZ/WebClient/Connector.py
> +        self.url_adr = endpoint
remove this line

2017-05-13 22:47 UTC, Dorrin93 commented on PZ/WebClient/Connector.py
> +        self.response = requests.get(self.url_adr)
`self.response = requests.get(endpoint)`

2017-05-13 22:47 UTC, Dorrin93 commented on PZ/WebClient/Connector.py
> +        self.url_adr += urllib.parse.urljoin(endpoint, 'values')
remove this line

2017-05-13 22:47 UTC, Dorrin93 commented on PZ/WebClient/Connector.py
> +        self.response = requests.get(self.url_adr, params=self.payload)
`self.response = requests.get(urljoin(endpoint, 'values'), params=self.payload)`

2017-05-13 22:47 UTC, Dorrin93 commented on PZ/WebClient/Connector.py
> +        self.url_adr += urllib.parse.urljoin(guid, 'values')
remove this line

2017-05-13 22:47 UTC, Dorrin93 commented on PZ/WebClient/Connector.py
> +        self.url_adr += urllib.parse.urljoin(guid, 'values')
remove this line

2017-05-13 22:47 UTC, Dorrin93 commented on PZ/WebClient/Connector.py
> +        self.response = requests.delete(self.url_adr)
`self.response = requests.delete(urljoin(self.url_adr, guid+'values'))`

2017-05-13 22:47 UTC, Dorrin93 commented on PZ/WebClient/Connector.py
> +        self.response = requests.delete(self.url_adr)
`self.response = requests.delete(urljoin(self.url_adr, guid))`

2017-05-14 09:40 UTC, Dorrin93 approved these changes

2017-05-14 09:40 UTC, merged